"""add_listing_fields

Revision ID: b3d3d4b931c8
Revises: 434d4c5bb8b6
Create Date: 2026-06-09 14:46:02.055387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d3d4b931c8'
down_revision: Union[str, Sequence[str], None] = '434d4c5bb8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('lot_size_sqft', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('roi', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('listings', sa.Column('seller_financing', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('listings', sa.Column('hoa', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('listings', sa.Column('hoa_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('listings', sa.Column('tax_exempt', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('listings', sa.Column('gated_community', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('listings', sa.Column('construction_status', sa.Text(), nullable=True))
    op.add_column('listings', sa.Column('year_built', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('features', sa.ARRAY(sa.Text()), server_default='{}', nullable=True))
    op.add_column('listings', sa.Column('maps_url', sa.Text(), nullable=True))
    op.add_column('listings', sa.Column('tag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'tag')
    op.drop_column('listings', 'maps_url')
    op.drop_column('listings', 'features')
    op.drop_column('listings', 'year_built')
    op.drop_column('listings', 'construction_status')
    op.drop_column('listings', 'gated_community')
    op.drop_column('listings', 'tax_exempt')
    op.drop_column('listings', 'hoa_fee')
    op.drop_column('listings', 'hoa')
    op.drop_column('listings', 'seller_financing')
    op.drop_column('listings', 'roi')
    op.drop_column('listings', 'lot_size_sqft')
    # ### end Alembic commands ###
